version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "netflix-lite-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-netflix-lite"
s3_prefix = "netflix-lite"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
resolve_image_repos = true