version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "netflix-lite-stack"
s3_bucket = "netflix-lite-frontend"
s3_prefix = "sam-artifacts"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []