version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "netflix-lite-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
resolve_image_repos = true