AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Netflix Lite API – Docker-based Lambda backend
yaml
# Add Tags for better resource management and cost tracking
Globals:
  Function:
    Timeout: 10
    Tags:
      Environment: Prod
      Project: NetflixLite

# Add VersioningConfiguration for S3 bucket to enable versioning
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      # Add encryption for better security
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

# Add security headers for CloudFront
  CloudFrontDistribution:
    Properties:
      DistributionConfig:
        # Add security headers
        ResponseHeadersPolicy:
          SecurityHeadersBehavior:
            ContentSecurityPolicy:
              Override: true
              ContentSecurityPolicy: "default-src 'self'"
            StrictTransportSecurity:
              Override: true
              AccessControlMaxAgeSec: 31536000
            XSSProtection:
              Override: true
              Protection: true
              ModeBlock: true

# Add DynamoDB backup configuration
  VideoTable:
    Properties:
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      # Add TTL for data lifecycle management if needed
      TimeToLiveSpecification:
        AttributeName: ExpirationTime
        Enabled: true
      # Add encryption
      SSESpecification:
        SSEEnabled: true

# Add environment variables for Lambda
  VideoAPI:
    Properties:
      Environment:
        Variables:
          TABLE_NAME: !Ref VideoTable
          REGION: !Ref AWS::Region
      # Add X-Ray tracing
      Tracing: Active
      # Add logging configuration
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Sub "/aws/lambda/${AWS::StackName}-VideoAPI"
Globals:
  Function:
    Timeout: 10

Parameters:
  S3BucketName:
    Type: String
    Default: !Sub "netflix-lite-${AWS::AccountId}-${AWS::Region}"
    Description: S3 bucket name for frontend hosting

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::OriginAccessIdentity
    Properties:
      OriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${S3BucketName}'

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub "${S3Bucket.Arn}/*"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Netflix Lite CloudFront Distribution
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100

  VideoAPI:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.11-v1
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /videos
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: Videos

  VideoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Videos
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  S3BucketName:
    Description: "S3 Bucket Name for Frontend"
    Value: !Ref S3Bucket
  S3WebsiteURL:
    Description: "S3 Website URL"
    Value: !GetAtt S3Bucket.WebsiteURL
  CloudFrontURL:
    Description: "CloudFront Distribution URL"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  DistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
